#docker build -t webis/wows-2024-baseline:0.0.1-beir -f Dockerfile.beir .
FROM pytorch/pytorch:latest

RUN apt-get update \
	&& DEBIAN_FRONTEND=noninteractive TZ=Etc/UTC apt-get install -y git openjdk-11-jdk build-essential \
	&& rm -rf /root/.cache

RUN pip3 install --no-dependencies ir_datasets \
	&& pip3 install tira pandas \
	&& rm -rf /root/.cache

# OMITTED: Move this to the real container
# RUN pip3 install beir pyserini
